version: '3.7'

# --------------------------------------------
# Define services to use.
# --------------------------------------------
services:


  endex:
    image: tunedmystic/endex
    build: .
    container_name: endex
    networks:
      - endex
    ports:
      - "8000:8000"
    env_file: ./env/dev.env
    environment:
      - BETTER_EXCEPTIONS=1
    volumes:
      - .:/app


  pg:
    image: postgres:11.2-alpine
    container_name: pg
    networks:
      - endex
    ports:
      - "5432:5432"
    env_file: ./env/dev.env


# --------------------------------------------
# Define networks to use.
# --------------------------------------------
networks:
  endex:
